title: Cambios de Forma Pokémon
theme: jekyll-theme-minimal
description: Exploración de las formas regionales y especiales de Pokémon
logo: AGUA.png
markdown: kramdown

include:
  - assets/css/style.css
